### ISSUE TITLE
'gs' directory does not exist 

### ISSUE THREAD

**Issue by WangzcBruce** [valeoai/PointBeV#5]
I hope this message finds you well. I am currently attempting to set up the PointBev environment and ran into an issue during the installation process. The installation instructions mention the following command:
cd pointbev/ops/gs; python setup.py build install; cd -
However, upon checking the repository's structure, I noticed that the 'gs' directory does not exist within the 'ops' directory. This has prevented me from completing the setup as instructed.
If cd the dir——defattn and run python setup.py develop, it still doesn't work.

**Comment by LoickCh** [comment]
Hey,
Yes, I had originally put it in an annex repo as a git submodule, it's been fixed, you should be able to continue the install.
