### ISSUE TITLE
Inquiry About Negative Training Loss During Model Training and Potential Causes

### ISSUE THREAD

**Issue by Johnny-Hu-406** [valeoai/PointBeV#7]
Thank you for your excellent work. I am very impressed with the results of your research. However, when I tried to reproduce your project, I followed the project instructions to set up the environment and train the model as directed. During training, the model's loss kept decreasing, but eventually, the training loss became less than 0. Could you please advise what might be causing this issue? I am using an RTX 4090 GPU.

![Screenshot from 2024-10-17 17-29-00](https://github.com/user-attachments/assets/f3cc3333-0a50-4f5e-a516-ab877eedd62d)

**Comment by LoickCh** [comment]
Hi,
Thank you for your message. The negative loss is not an issue. I followed what is done in FIERY, i.e you have a learnable parameter such that you compute: 
     - loss * weight + uncertainty
https://github.com/valeoai/PointBeV/blob/main/pointbev/models/trainer.py#L340

Where uncertainty is 0.5*weight:
https://github.com/valeoai/PointBeV/blob/main/pointbev/loss/common.py#L130

It happens that this sum is negative. 

And the justification from FIERY comes from this paper:
https://arxiv.org/abs/1705.07115 cited as 24 in the FIERY paper.

You can find useful info in FIERY code here:
https://github.com/wayveai/fiery/blob/fd03f164935ac172ef6d96117a7a4873abf23919/fiery/trainer.py#L54
https://github.com/wayveai/fiery/blob/fd03f164935ac172ef6d96117a7a4873abf23919/fiery/trainer.py#L95

**Comment by Johnny-Hu-406** [comment]
Hi,
If I understand correctly, my question pertains to the following sentence in your paper:

“We train our model using a segmentation, an offset, and a centerness loss as in FIERY.”

Thank you for your thorough response to my question; it has deepened my understanding of this question.
